dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path("dashboard/", views.homeDashboard, name='dashboard'),
]

rapport/urls.py
from django.urls import path
from . import views

app_name = 'rapport'

urlpatterns = [
    path('rapport/', views.rapport, name='rapport'),
]

student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    path('student/', views.homeEleve, name='student_list'),
    path('addStudent/', views.addStudent, name='addStudent'),
    path('update_student/<int:id>', views.updateStudent, name='update_student'),
    path('delete_student/<int:id>', views.delete_student, name='delete_student'), 



]

teacher/urls.py
from django.urls import path # type: ignore
from . import views


app_name = 'teacher'

urlpatterns = [
    path('list_teacher/', views.home_teacher, name='list_teacher'),
    path('add_teacher/', views.add_teacher, name='add_teacher'),
    path('update_teacher/<int:id>', views.update_teacher, name='update_teacher'),
    path('delete_teacher/<int:id>', views.delete_teacher, name='delete_teacher'),


]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('list_user', views.list_user, name='list_user'),
    # path('add_user', views.add_user, name='add_user'),
    path('add_user', views.add_auth_user, name='add_user'),

    path('update_user/<int:id>', views.update_user, name='update_user'),
    path('delete_user/<int:id>', views.delete_user, name='delete_user'),



]

website/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('', include('student.urls')),
    path('', include('teacher.urls')),
    path('', include('user.urls')),
    path('', include('rapport.urls')),



]

teacher/models.py
from django.db import models

# Create your models here.

matiere = {
    ("MATH", "MATHEMATIQUE"),
   ("PHY", "PHYSIQUE"),
   ("SVT", "SVT")
}

class Teacher(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    sexe = models.BooleanField(default=False)
    date_de_naissance = models.CharField(max_length=255)
    matiere = models.CharField(max_length=25,choices=matiere)
    numero_de_telephone = models.CharField(max_length=15)
    ville = models.CharField(max_length=15)
    vacant = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.first_name} {self.last_name} : matiere de {self.matiere}'

teacher/forms.py
from django import forms
from . import models


class TeacherForms(forms.Form):
    first_name = forms.CharField(max_length=10)
    last_name = forms.CharField(max_length=10)

class TeacherFormModel(forms.ModelForm):
    class Meta:
        model = models.Teacher
        fields = '__all__'

    

teacher/views.py
from django.shortcuts import redirect, render
from .forms import *
from .models import *

# Create your views here.

def home_teacher(request):
    teachers = Teacher.objects.all()
    context = {
        'teachers': teachers
    }
    return render(request, 'teacher/list_teacher.html', context)

def add_teacher(request):
    teachers = TeacherFormModel()
    if request.method == 'POST':
        teachers = TeacherFormModel(request.POST)
        if teachers.is_valid():
            teachers.save()
            return redirect('teacher:list_teacher') 

    context = {
        'teachers':teachers,
        'title' : 'Ajouter professeur'
        } 
    return render(request, 'teacher/add_teacher.html', context)

def update_teacher(request, id):
    context = {
        'title' : 'Modifier professeur'
    }
    teacher = Teacher.objects.get(id = id)
    if request.method == 'POST':
        teacher_form = TeacherFormModel(request.POST, instance=teacher)
        if teacher_form.is_valid():
            print(f"teacher_form : {teacher_form}")
            teacher_form.save()
            return redirect('teacher:list_teacher') 
    
    teacher_form = TeacherFormModel(instance=teacher)
    context["teachers"] = teacher_form
    return render(request, 'teacher/add_teacher.html', context)

def delete_teacher(request, id):
    teacher = Teacher.objects.get(id = id )
    teacher.delete()
    return redirect('teacher:list_teacher')

teacher/templates/teacher/add_teacher.html
{% extends "sidebar.html" %}
{% load static %}


 {% block content %}

    <section class="inscription">
        <h2 class="titre">{{ title }}</h2>
        <form action="" method="post" class="box-form" enctype="multipart/form-data">
            {% csrf_token %}

            {{ teachers }} 

            <div class="btn">
                <button type="submit" name="inscrire" class="annuler"> <a href="{% url 'teacher:list_teacher' %}"> Annuler </a> </button>
                <button type="submit" name="enregistrer" class="inscrire"> Enregistrer </button>
            </div>
            
        </form>
    </section>
 
 {% endblock content %}

teacher/templates/teacher/list_teacher.html
{% extends "sidebar.html" %}


{% block header %}

    <header>
        <div class="container">
            <h1><i class="fas fa-pencil-alt"></i>MonEtab</h1>
            <ul>
                <li><a href="{% url 'dashboard:dashboard' %}"><i class="fas fa-tachometer-alt" ></i> Tableau de bord</a></li>
                <li><a href="{% url 'student:student_list' %}" class="active"><i class="fas fa-book-reader" ></i> Elèves</a></li>
                <li><a href="{% url 'teacher:list_teacher' %}"><i class="fas fa-chalkboard-teacher" ></i> Professeurs</a></li>
                <li><a href="{% url 'user:list_user' %}"><i class="fas fa-user" ></i> Utilisateurs</a></li>
                <li><a href="{% url 'rapport:rapport' %}"><i class="fas fa-file-alt" ></i> Rapport</a></li>
                <li><a href="index.html"><i class="fas fa-sign-out-alt" style="color: rgb(248, 59, 75);"></i> Déconnexion</a></li>
            </ul>
        </div>
    </header>

{% endblock header %}

{% block content %}

<div class="main">

    <div class="table-container">
        <div class="row">
            <div class="col-10">
                <h2>Informations sur les Professeurs</h2>
            </div>
            <div class="col-2">
                <li><a href="{% url 'teacher:add_teacher' %}" style="color: rgb(72, 71, 71);"><i class="fas fa-plus-circle" ></i> Ajouter un Professeur </a></li>
            </div>
        </div>
        <div class="row">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Matière</th>
                        <th>Vacant</th>
                        <th>Age</th>
                        <th>Téléphone</th>
                        <th>Ville</th>
                        <th>Actions</th>
                    </tr>
                </thead> 
                <tbody>
                    {% if teachers %}
                        {% for teacher in teachers %}

                            <tr>
                                <td>{{ teacher.first_name }}</td>
                                <td>{{ teacher.last_name }}</td>
                                <td>{{ teacher.matiere }}</td>
                                <td>{{ teacher.vacant }}</td>
                                <td>{{ teacher.date_de_naissance }}</td>
                                <td>{{ teacher.numero_de_telephone }}</td>
                                <td>{{ teacher.ville }}</td>
                                <td><a href="{% url 'teacher:update_teacher' teacher.id %}" class="modifier"> Modifier</a><a onclick="notif({{teacher.id}})" class="supprimer">Supprimer</a></td>
                            </tr>
                        
                        {% endfor %}
                    
                    {% else %}
                            <tr>
                                <td>
                                    <h1>
                                        No Informations Yet
                                    </h1>
                                </td>
                            </tr>
                    {% endif %}
                    
                </tbody>
            </table>
        </div>
        
    </div>

</div>

{% endblock content %}

{% block notif_javascript %}
    <script>
        function notif(teacher){
            const deleteUrl = "{% url 'teacher:delete_teacher' 0 %}".replace('0', teacher); 
            Swal.fire({
            title: "Etes vous sur de supprimer ?",
            icon: "question",
            iconHtml: "?",
            confirmButtonText: `Oui`,
            cancelButtonText: "Non",
            showCancelButton: true,
            showCloseButton: true
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = deleteUrl;  // Redirect to the dynamically generated URL
            }
        });
        }
    </script>

    

{% endblock notif_javascript %}