dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path("dashboard/", views.homeDashboard, name='dashboard'),
]

rapport/urls.py
from django.urls import path
from . import views

app_name = 'rapport'

urlpatterns = [
    path('rapport/', views.rapport, name='rapport'),
]

student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    path('student/', views.homeEleve, name='student_list'),
    path('addStudent/', views.addStudent, name='addStudent'),
    path('update_student/<int:id>', views.updateStudent, name='update_student'),
    path('delete_student/<int:id>', views.delete_student, name='delete_student'), 



]

teacher/urls.py
from django.urls import path # type: ignore
from . import views


app_name = 'teacher'

urlpatterns = [
    path('list_teacher/', views.home_teacher, name='list_teacher'),
    path('add_teacher/', views.add_teacher, name='add_teacher'),
    path('update_teacher/<int:id>', views.update_teacher, name='update_teacher'),
    path('delete_teacher/<int:id>', views.delete_teacher, name='delete_teacher'),


]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('list_user', views.list_user, name='list_user'),
    # path('add_user', views.add_user, name='add_user'),
    path('add_user', views.add_auth_user, name='add_user'),

    path('update_user/<int:id>', views.update_user, name='update_user'),
    path('delete_user/<int:id>', views.delete_user, name='delete_user'),



]

website/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('', include('student.urls')),
    path('', include('teacher.urls')),
    path('', include('user.urls')),
    path('', include('rapport.urls')),



]

user/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    pseudo = models.CharField(max_length=250, unique=True)
    password = models.CharField(max_length=250,)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.pseudo} : {self.password}'
    
    # class Meta:
    #     verbose_name = 'Student'
    #     verbose_name_plural = 'Utilisateurs'
    

user/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User


class UserForms(forms.Form):
    first_name = forms.CharField(max_length=10)
    last_name = forms.CharField(max_length=10)
    created_at = forms.DateField()


class UserFormsModel(forms.ModelForm):
    class Meta:
        model = User 
        fields = "__all__"
        exclude = ["created_at"]

user/views.py
from django.shortcuts import redirect, render
from .forms import *
from . import models
from django.contrib.auth.models import User

from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required

# Create your views here.


def list_user(request):

    users = User.objects.all()
    context = {
        'users': users
    }
    print(f"")
    return render(request, 'user/list_user.html', context)

def add_user(request):
    form = UserFormsModel()
    if request.method == 'POST':
        form = UserFormsModel(request.POST)
        if form.is_valid():
            form.save()
            return redirect('user:list_user')


    context = {
        'user_form':form,
        'title': 'Ajouter utilisateur'
    }
    # return render(request, 'user/add_user.html',context)
    return render(request, 'user/forms.html',context)


def update_user(request, id):
    context = {
        'title': 'Modifier utilisateur'
    }
    user = User.objects.get(id = id)
    if request.method == 'POST':
        user_form = UserFormsModel(request.POST, instance=user) 
        if user_form.is_valid():
            print(f"user_form : {user_form}")
            user_form.save()
            return redirect('user:list_user') 
    
    user_form = UserFormsModel(instance=user)
    context["user_form"] = user_form

    # return render(request, 'user/update_user.html', context)
    return render(request, 'user/forms.html',context)


def delete_user(request, id):
    user = User.objects.get(id = id ) 
    user.delete()
    return redirect('user:list_user') 

def add_auth_user(request):
    if request.method == 'POST':
        pseudo = request.POST["username"]
        password = request.POST["password"]
        if not pseudo or not password:
            print(f"Nous sommes ici !")
            return redirect('user:add_user')


        user = User(username = pseudo)
        user.save()
        user.password = password
        user.set_password(user.password)
        user.save()
    context = {
        'title': 'Ajouter utilisateur'
    }

    return render(request, 'user/forms.html',context)
    

user/templates/user/forms.html
{% extends "sidebar.html" %}

{% load static %}

{% block content %}
<section class="inscription">
    <h2 class="titre"><i class="fas fa-pencil-alt"> {{ title }} </h2>
    <form action="" method="post" class="box-form" enctype="multipart/form-data">
        {% csrf_token %}

        {% comment %} {{ user_form }} {% endcomment %}

        <div class="form-group">
            <label for="name"><i class="zmdi zmdi-account material-icons-name"></i></label>
            <input type="text" name="userame" id="name" placeholder="Your Name"/>
        </div>
        <div class="form-group">
            <label for="pass"><i class="zmdi zmdi-lock"></i></label>
            <input type="password" name="password" id="pass" placeholder="Password"/>
        </div>
        <div class="btn">
            <button type="submit" name="inscrire" class="annuler"><a href="{% url 'user:list_user' %}"> Annuler </a></button>
            <button type="submit" name="enregistrer" class="inscrire">Enregistrer</button>
        </div>
        
    </form>
</section>
{% endblock content %}

user/templates/user/list_user.html
{% extends "sidebar.html" %}


{% block header %}

    <header>
        <div class="container">
            <h1><i class="fas fa-pencil-alt"></i>MonEtab</h1>
            <ul>
                <li><a href="{% url 'dashboard:dashboard' %}"><i class="fas fa-tachometer-alt" ></i> Tableau de bord</a></li>
                <li><a href="{% url 'student:student_list' %}" class="active"><i class="fas fa-book-reader" ></i> Elèves</a></li>
                <li><a href="{% url 'teacher:list_teacher' %}"><i class="fas fa-chalkboard-teacher" ></i> Professeurs</a></li>
                <li><a href="{% url 'user:list_user' %}"><i class="fas fa-user" ></i> Utilisateurs</a></li>
                <li><a href="{% url 'rapport:rapport' %}"><i class="fas fa-file-alt" ></i> Rapport</a></li>
                <li><a href="index.html"><i class="fas fa-sign-out-alt" style="color: rgb(248, 59, 75);"></i> Déconnexion</a></li>
            </ul>
        </div>
    </header>

{% endblock header %}

{% block content %}

<div class="main">

    <div class="table-container">
        <div class="row">
            <div class="col-10">
                <h2>Informations sur les Utilisateurs</h2>
            </div>
            <div class="col-2">
                <li><a href="{% url 'user:add_user' %}" style="color: rgb(72, 71, 71);"><i class="fas fa-plus-circle" ></i> Ajouter un Professeur </a></li>
            </div>
        </div>
        <div class="row">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Pseudo</th>
                        <th>Date de création </th>
                        <th>Actions </th>
                        

                    </tr>
                </thead>
                <tbody>
                    {% if users %}
                        {% for user in users %}

                            <tr>
                                <td>{{ user.username }}</td>
                                <td>{{ user.date_joined | date:"Y-m-d" }}</td>
                                <td><a href="{% url 'user:update_user' user.id %}" class="modifier"> Modifier</a><a onclick="notif({{user.id}})" class="supprimer">Supprimer</a></td>
                            </tr>
                        {% endfor %}
                    
                    {% else %}
                            <tr>
                                <td>
                                    <h1>
                                        No Informations Yet
                                    </h1>
                                </td>
                            </tr>
                    {% endif %}
                    
                </tbody>
            </table>
        </div>
        
    </div>

</div>

{% endblock content %}

{% block notif_javascript %}

    <script>
        function notif(user){
            const deleteUrl = "{% url 'user:delete_user' 0 %}".replace('0', user); 
            Swal.fire({
            title: "Etes vous sur de supprimer ?",
            icon: "question",
            iconHtml: "?",
            confirmButtonText: `Oui`,
            cancelButtonText: "Non",
            showCancelButton: true,
            showCloseButton: true
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = deleteUrl;  // Redirect to the dynamically generated URL
            }
        });
        
        }
    </script>

{% endblock notif_javascript %}