dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path("dashboard/", views.homeDashboard, name='dashboard'),
]

rapport/urls.py
from django.urls import path
from . import views

app_name = 'rapport'

urlpatterns = [
    path('rapport/', views.rapport, name='rapport'),
]

student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    path('student/', views.homeEleve, name='student_list'),
    path('addStudent/', views.addStudent, name='addStudent'),
    path('update_student/<int:id>', views.updateStudent, name='update_student'),
    path('delete_student/<int:id>', views.delete_student, name='delete_student'), 



]

teacher/urls.py
from django.urls import path # type: ignore
from . import views


app_name = 'teacher'

urlpatterns = [
    path('list_teacher/', views.home_teacher, name='list_teacher'),
    path('add_teacher/', views.add_teacher, name='add_teacher'),
    path('update_teacher/<int:id>', views.update_teacher, name='update_teacher'),
    path('delete_teacher/<int:id>', views.delete_teacher, name='delete_teacher'),


]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('list_user', views.list_user, name='list_user'),
    # path('add_user', views.add_user, name='add_user'),
    path('add_user', views.add_auth_user, name='add_user'),

    path('update_user/<int:id>', views.update_user, name='update_user'),
    path('delete_user/<int:id>', views.delete_user, name='delete_user'),



]

website/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('', include('student.urls')),
    path('', include('teacher.urls')),
    path('', include('user.urls')),
    path('', include('rapport.urls')),



]

student/models.py
from django.db import models

# Create your models here.



class Eleve(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    sexe = models.CharField(max_length=255)
    matricule = models.CharField(max_length=255)
    classe = models.CharField(max_length=255)
    date_naissance = models.CharField(max_length=255)
    numero_telephone = models.CharField(max_length=255)
    ville = models.CharField(max_length=255)
    

student/forms.py
from django import forms
from .models import *

class StudentForms(forms.Form):
    first_name = forms.CharField(max_length=10)
    last_name = forms.CharField(max_length=10)

class StudentFormModel(forms.ModelForm):
    class Meta :
        model = Eleve
        fields = '__all__' 

student/views.py
from django.shortcuts import redirect, render
from .forms import *
from .models import *

# Create your views here.


def homeEleve(request):
    students = Eleve.objects.all()
    context = {
        'students':students
    }
    return render(request, 'eleve/student_list.html',context)

def addStudent(request):
    students = StudentFormModel()
    if request.method == 'POST':
        students = StudentFormModel(request.POST)
        if students.is_valid():
            students.save()
            return redirect('student:student_list')
        
    context = {
        'students': students ,
        'title' : 'Ajouter eleve',
        } 
    return render(request, 'eleve/add_student.html', context)

def updateStudent(request, id):
    context = {
        'title':'Modifier eleve'
    }
    student = Eleve.objects.get(id=id)
    if request.method == 'POST':
        students = StudentFormModel(request.POST, instance=student) 
        if students.is_valid():
            students.save()
            return redirect('student:student_list')
        
    students = StudentFormModel(instance=student)
    context["students"] = students

    return render(request, 'eleve/add_student.html', context)

def delete_student(request, id):
    student = Eleve.objects.get(id=id)
    student.delete() 
    return redirect('student:student_list')

student/templates/eleve/add_student.html
{% extends "sidebar.html" %}
{% load static %}
 

{% block content %}

    <section class="inscription">
        <h2 class="titre"> {{ title }} </h2>
        <form action="" method="post" class="box-form" enctype="multipart/form-data">
            {% csrf_token %}

            {{ students }}
            
            <div class="btn">
                <button type="submit" name="inscrire" class="annuler"><a href="{% url 'student:student_list' %}"> Annuler </a> </button>
                <button type="submit" name="enregistrer" class="inscrire">Enregistrer</button>
            </div>
            
        </form>
    </section>

{% endblock content %}

{% block notif_javascript %}

    <script>
        function notif(student){
            var elt = '{% url "student:delete_student" 0 %}'.replace('0',student)
            Swal.fire({
            title: "Etes vous sur de supprimer ?",
            icon: "question",
            iconHtml: "?",
            confirmButtonText: "Oui",
            cancelButtonText: "Non",
            showCancelButton: true,
            showCloseButton: true
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = elt
            }
        })
        ;
        }
    </script>

{% endblock notif_javascript %}

student/templates/eleve/sidebar.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tableau de bord - MonEtab</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
</head>
<body>
    {% block header %}{% endblock header %}


    <div class="main-container">
        {% block content %}{% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        function notif(){
            Swal.fire({
            title: "Etes vous sur de supprimer ?",
            icon: "question",
            iconHtml: "?",
            confirmButtonText: "Oui",
            cancelButtonText: "Non",
            showCancelButton: true,
            showCloseButton: true
        });
        }
    </script>
</body>
</html>

student/templates/eleve/student_list.html
{% extends "sidebar.html" %}

{% block header %}

    <header>
        <div class="container">
            <h1><i class="fas fa-pencil-alt"></i>MonEtab</h1>
            <ul>
                <li><a href="{% url 'dashboard:dashboard' %}"><i class="fas fa-tachometer-alt" ></i> Tableau de bord</a></li>
                <li><a href="{% url 'student:student_list' %}" class="active"><i class="fas fa-book-reader" ></i> Elèves</a></li>
                <li><a href="{% url 'teacher:list_teacher' %}"><i class="fas fa-chalkboard-teacher" ></i> Professeurs</a></li>
                <li><a href="{% url 'user:list_user' %}"><i class="fas fa-user" ></i> Utilisateurs</a></li>
                <li><a href="{% url 'rapport:rapport' %}"><i class="fas fa-file-alt" ></i> Rapport</a></li>
                <li><a href="index.html"><i class="fas fa-sign-out-alt" style="color: rgb(248, 59, 75);"></i> Déconnexion</a></li>
            </ul>
        </div>
    </header>

{% endblock header %}

{% block content %}

    <div class="main">
        <div class="table-container">

            <div class="row">
                <div class="col-10">
                    <h2>Informations sur les Elèves</h2>
                </div>
                <div class="col-2">
                    <li><a href="{% url 'student:addStudent' %}" style="color: rgb(72, 71, 71);"><i class="fas fa-plus-circle" ></i> Ajouter un élève </a></li>
                </div>
            </div>
            <div class="row">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Prénom</th>
                            <th>Genre</th>
                            <th>Classe</th>
                            <th>Matricule</th>
                            <th>Age</th>
                            <th>Téléphone</th>
                            <th>Ville</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if students %}

                            {% for student in students %}
                                <tr>
                                
                                    <td>{{ student.first_name}}</td>
                                    <td>{{ student.last_name}}</td>
                                    <td>{{ student.sexe}}</td>
                                    <td>{{ student.classe}}</td>
                                    <td>{{ student.matricule}}</td>
                                    <td>{{ student.date_naissance}}</td>
                                    <td>{{ student.numero_telephone}}</td>
                                    <td>{{ student.ville}}</td>
                                    <td><a href="{% url 'student:update_student' student.id %}" class="modifier"> Modifier</a><a onclick="notif({{ student.id }})" class="supprimer">Supprimer</a></td>
                                </tr>
                            {% endfor %}
                                 
                            
                        {% else %}
                            <tr>
                                <td>
                                    <h1>
                                        No Informations Yet
                                    </h1>
                                </td>
                            </tr>
                        {% endif %}
                        

                        <!-- Ajouter d'autres lignes pour plus d'artisans -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock content %}

{% block notif_javascript %}
<script>
    function notif(teacher){
        const deleteUrl = "{% url 'student:delete_student' 0 %}".replace('0', teacher); 
        Swal.fire({
        title: "Etes vous sur de supprimer ?",
        icon: "question",
        iconHtml: "?",
        confirmButtonText: `Oui`,
        cancelButtonText: "Non",
        showCancelButton: true,
        showCloseButton: true
    }).then((result) => {
        if (result.isConfirmed) {
            window.location.href = deleteUrl;  // Redirect to the dynamically generated URL
        }
    });
    }
</script>

{% endblock notif_javascript %}